# Generated by Django 6.1.1 on 2026-09-15 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public verification code embedded in the QR code.', unique=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('REVOKED', 'Revoked')], db_index=True, default='VALID', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='confirmation_slips/%Y/%m/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_slip', to='applications.application')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['verification_code'], name='confirmatio_verific_f4db07_idx'), models.Index(fields=['status'], name='confirmatio_status_8f5923_idx')],
            },
        ),
    ]
