# Generated by Django 6.1.1 on 2026-09-15 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Registration'), ('PROFILE_UPDATE', 'Profile Update'), ('DOCUMENT_UPLOAD', 'Document Upload'), ('DOCUMENT_REPLACE', 'Document Replacement'), ('DOCUMENT_REVIEW', 'Document Review'), ('APPLICATION_SUBMIT', 'Application Submission'), ('APPLICATION_REVIEW', 'Application Review'), ('CORRECTION_REQUEST', 'Correction Request'), ('APPLICATION_APPROVE', 'Application Approval'), ('APPLICATION_REJECT', 'Application Rejection'), ('SLIP_GENERATE', 'Confirmation Slip Generation'), ('SLIP_REVOKE', 'Confirmation Slip Revocation'), ('ROLE_CHANGE', 'User Role Modification'), ('ACCOUNT_DEACTIVATE', 'Account Deactivation'), ('ACCOUNT_REACTIVATE', 'Account Reactivation'), ('ADMISSION_IMPORT', 'Admission Record Import'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_type', models.CharField(blank=True, max_length=60)),
                ('target_id', models.CharField(blank=True, max_length=60)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
