# Generated by Django 6.1.1 on 2026-09-15 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g., 2024/2025', max_length=20, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one session should be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(help_text='Short code used in references, e.g. CSC, BCH.', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('degree_type', models.CharField(choices=[('BSC', 'B.Sc.'), ('BA', 'B.A.'), ('BENG', 'B.Eng.'), ('MBBS', 'M.B.B.S.'), ('LLB', 'LL.B.'), ('OTH', 'Other')], default='BSC', max_length=10)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='admissions.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jamb_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('admission_number', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_admissions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_records', to='admissions.admissionsession')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_records', to='admissions.department')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_records', to='admissions.programme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_programme_per_department'),
        ),
        migrations.AddIndex(
            model_name='admissionrecord',
            index=models.Index(fields=['jamb_number'], name='admissions__jamb_nu_eb640d_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionrecord',
            index=models.Index(fields=['admission_number'], name='admissions__admissi_1a8df3_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionrecord',
            index=models.Index(fields=['status'], name='admissions__status_edd724_idx'),
        ),
    ]
