# Generated by Django 6.1.1 on 2026-09-15 13:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7 to 15 digits, optional leading +).', regex='^\\+?[0-9]{7,15}$')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('state_of_origin', models.CharField(blank=True, max_length=50)),
                ('lga', models.CharField(blank=True, max_length=80, verbose_name='Local Government Area')),
                ('residential_address', models.TextField(blank=True)),
                ('jamb_number', models.CharField(blank=True, db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='JAMB number must be 8 to 12 digits.', regex='^[0-9]{8,12}$')])),
                ('admission_number', models.CharField(blank=True, db_index=True, max_length=30)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('is_complete', models.BooleanField(default=False, help_text='Set to True once all required fields are filled.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'indexes': [models.Index(fields=['jamb_number'], name='accounts_st_jamb_nu_53843e_idx'), models.Index(fields=['admission_number'], name='accounts_st_admissi_ed2323_idx')],
            },
        ),
    ]
