# Generated by Django 6.1.1 on 2026-09-16 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_record',
            field=models.OneToOneField(blank=True, help_text='The admission record this student claimed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to='admissions.admissionrecord'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
