"""
PDF generation for confirmation slips using ReportLab.

The PDF is intentionally plain (no external fonts) so it renders the same
on every platform and does not require installing system packages.
"""

import io
from datetime import datetime

from django.conf import settings
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from .qr import generate_qr_png, verification_url


UNIVERSITY_NAME = "USMANU DANFODIYO UNIVERSITY, SOKOTO"
UNIVERSITY_SUB = "P.M.B. 2346, Sokoto, Nigeria"
SLIP_TITLE = "STUDENT CONFIRMATION SLIP"


def build_slip_pdf(*, slip) -> io.BytesIO:
    """
    Return an in-memory PDF of the confirmation slip.
    """
    application = slip.application
    student = application.student
    profile = student.student_profile
    record = application.admission_record

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
        title=f"Confirmation Slip — {application.reference}",
        author=UNIVERSITY_NAME,
    )

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], alignment=1, fontSize=16, leading=20, spaceAfter=2)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], alignment=1, fontSize=11, leading=14, textColor=colors.grey)
    h3 = ParagraphStyle("h3", parent=styles["Heading3"], alignment=1, fontSize=13, leading=16, spaceBefore=6, spaceAfter=10)
    body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=10, leading=14)
    small = ParagraphStyle("small", parent=styles["BodyText"], fontSize=8, textColor=colors.grey)

    story = []

    # Header
    story.append(Paragraph(UNIVERSITY_NAME, h1))
    story.append(Paragraph(UNIVERSITY_SUB, h2))
    story.append(Spacer(1, 6))
    story.append(Paragraph(SLIP_TITLE, h3))

    # Student info table
    info_rows = [
        ["Full name", profile.full_name or student.get_full_name() or student.username],
        ["Admission number", record.admission_number or "—"],
        ["JAMB number", record.jamb_number],
        ["Department", record.department.name],
        ["Programme", record.programme.name],
        ["Admission session", record.session.name],
        ["Application reference", str(application.reference)],
        ["Verification code", str(slip.verification_code)],
        ["Confirmation date", slip.generated_at.strftime("%B %d, %Y %H:%M")],
    ]
    table = Table(info_rows, colWidths=[55 * mm, 100 * mm])
    table.setStyle(
        TableStyle(
            [
                ("FONT", (0, 0), (-1, -1), "Helvetica", 10),
                ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 10),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#0a4d3c")),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("LINEBELOW", (0, 0), (-1, -2), 0.25, colors.lightgrey),
                ("BOX", (0, 0), (-1, -1), 0.4, colors.grey),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 8 * mm))

    # QR code + verification URL
    qr_io = generate_qr_png(slip.verification_code)
    qr_image = Image(qr_io, width=40 * mm, height=40 * mm)
    url_text = Paragraph(
        f"Verify at: <font color='blue'>{verification_url(slip.verification_code)}</font><br/>"
        f"Or scan the QR code on the right.",
        body,
    )
    qr_table = Table([[url_text, qr_image]], colWidths=[115 * mm, 40 * mm])
    qr_table.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
    story.append(qr_table)
    story.append(Spacer(1, 6 * mm))

    # Disclaimer
    story.append(
        Paragraph(
            "This slip was generated by the Online Student Confirmation and Document "
            "Verification System. The QR code confirms that the slip exists in the "
            "university's records. It does <b>not</b> by itself certify the authenticity "
            "of every uploaded document. Final verification is performed by authorised "
            "university officers.",
            small,
        )
    )

    if slip.generated_by:
        story.append(Spacer(1, 4 * mm))
        story.append(
            Paragraph(
                f"Generated by: {slip.generated_by.get_full_name() or slip.generated_by.username}",
                small,
            )
        )

    doc.build(story)
    buffer.seek(0)
    return buffer